name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4  # Mise à jour de v3 à v4 pour la compatibilité avec Node.js 20

    # 2. Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Mise à jour de v1 à v2 pour utiliser Buildx
    
    # 3. Login to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3  # Mise à jour de v2 à v3 pour la compatibilité avec Node.js 20
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 4. Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v3  # Mise à jour à la dernière version stable
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/my-app:latest  # Remplacez 'my-app' par le nom de votre app
